# Generated by Django 5.2.7 on 2025-10-13 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpenses',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
