# Generated by Django 5.2.6 on 2025-11-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpenses',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
