# Generated by Django 5.2.6 on 2025-11-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda_app', '0002_alter_otherexpenses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
