# Generated by Django 5.2.6 on 2025-11-23 07:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda_app', '0004_notification_pricecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Budget',
                'verbose_name_plural': 'Category Budgets',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
