# Generated by Django 5.2.6 on 2025-11-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sda_app', '0005_categorybudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='otherexpenses',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=50),
        ),
    ]
